=== YxWMDS/pz8/src/Devices.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="devices">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="device" type="device" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="device">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="origin" type="xs:string" />
            <xs:element name="price" type="xs:integer" />
            <xs:element name="type">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="isPeripheral" type="xs:boolean" />
                        <xs:element name="energy" type="xs:positiveInteger" />
                        <xs:element name="hasCooler" type="xs:boolean" />
                        <xs:element name="componentGroup" type="xs:string" />
                        <xs:element name="port" type="xs:string" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="id" type="xs:string" />
    </xs:complexType>

</xs:schema>

=== YxWMDS/pz8/src/Devices.xml
<?xml version="1.0" encoding="UTF-8"?>

<devices xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="Devices.xsd">

    <device id ="1">
        <name>video card</name>
        <origin>Mexico</origin>
        <price>100</price>
        <type>
            <isPeripheral>true</isPeripheral>
            <energy>1</energy>
            <hasCooler>true</hasCooler>
            <componentGroup>multimedia</componentGroup>
            <port>usb</port>
        </type>
    </device>

    <device id ="2">
        <name>processor</name>
        <origin>USA</origin>
        <price>200</price>
        <type>
            <isPeripheral>true</isPeripheral>
            <energy>2</energy>
            <hasCooler>false</hasCooler>
            <componentGroup>multimedia</componentGroup>
            <port>com</port>
        </type>
    </device>

    <device id ="3">
        <name>flash</name>
        <origin>Belarus</origin>
        <price>50</price>
        <type>
            <isPeripheral>false</isPeripheral>
            <energy>0</energy>
            <hasCooler>false</hasCooler>
            <componentGroup>data</componentGroup>
            <port>usb</port>
        </type>
    </device>

</devices>
